---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:e13d489153410a8548bff216ac2f6063c4ac96501efe72994d2af85f1ed7bc02
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
