---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:613d92cb045ea9ac965476dbc26c6552ebe8df626e18266b316f771e53a2ba3e
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
