---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-operators
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceType: grpc
  image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index@sha256:e1e0c873eb8aaf054adb4a77cc89d0a9f3d02a685963b25723f53ea853c432fe
  displayName: custom-operators
  updateStrategy:
    registryPoll:
      interval: 30m
